<h1>Case Study #3 - Foodie-Fi</h1>

<h2 id="introduction">Introduction</h2>

<p>Subscription based businesses are super popular and Danny realised that there was a large gap in the market - he wanted to create a new streaming service that only had food related content - something like Netflix but with only cooking shows!</p>

<p>Danny finds a few smart friends to launch his new startup Foodie-Fi in 2020 and started selling monthly and annual subscriptions, giving their customers unlimited on-demand access to exclusive food videos from around the world!</p>

<p>Danny created Foodie-Fi with a data driven mindset and wanted to ensure all future investment decisions and new features were decided using data. This case study focuses on using subscription style digital data to answer important business questions.</p>

<h2 id="available-data">Available Data</h2>

<p>Danny has shared the data design for Foodie-Fi and also short descriptions on each of the database tables - our case study focuses on only 2 tables but there will be a challenge to create a new table for the Foodie-Fi team.</p>

<p>All datasets exist within the <code class="language-plaintext highlighter-rouge">foodie_fi</code> database schema - be sure to include this reference within your SQL scripts as you start exploring the data and answering the case study questions.</p>

<h3 id="entity-relationship-diagram">Entity Relationship Diagram</h3>

<p><img src='https://8weeksqlchallenge.com/images/case-study-3-erd.png'/></p>

<h3 id="table-1-plans">Table 1: plans</h3>

<p>Customers can choose which plans to join Foodie-Fi when they first sign up.</p>

<p>Basic plan customers have limited access and can only stream their videos and is only available monthly at $9.90</p>

<p>Pro plan customers have no watch time limits and are able to download videos for offline viewing. Pro plans start at $19.90 a month or $199 for an annual subscription.</p>

<p>Customers can sign up to an initial 7 day free trial will automatically continue with the pro monthly subscription plan unless they cancel, downgrade to basic or upgrade to an annual pro plan at any point during the trial.</p>

<p>When customers cancel their Foodie-Fi service - they will have a <code class="language-plaintext highlighter-rouge">churn</code> plan record with a <code class="language-plaintext highlighter-rouge">null</code> price but their plan will continue until the end of the billing period.</p>

<div class="responsive-table">

  <table>
    <thead>
      <tr>
        <th>plan_id</th>
        <th>plan_name</th>
        <th>price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>0</td>
        <td>trial</td>
        <td>0</td>
      </tr>
      <tr>
        <td>1</td>
        <td>basic monthly</td>
        <td>9.90</td>
      </tr>
      <tr>
        <td>2</td>
        <td>pro monthly</td>
        <td>19.90</td>
      </tr>
      <tr>
        <td>3</td>
        <td>pro annual</td>
        <td>199</td>
      </tr>
      <tr>
        <td>4</td>
        <td>churn</td>
        <td>null</td>
      </tr>
    </tbody>
  </table>

</div>

<h3 id="table-2-subscriptions">Table 2: subscriptions</h3>

<p>Customer subscriptions show the exact date where their specific <code class="language-plaintext highlighter-rouge">plan_id</code> starts.</p>

<p>If customers downgrade from a pro plan or cancel their subscription - the higher plan will remain in place until the period is over - the <code class="language-plaintext highlighter-rouge">start_date</code> in the <code class="language-plaintext highlighter-rouge">subscriptions</code> table will reflect the date that the actual plan  changes.</p>

<p>When customers upgrade their account from a basic plan to a pro or annual pro plan - the higher plan will take effect straightaway.</p>

<p>When customers churn - they will keep their access until the end of their current billing period but the <code class="language-plaintext highlighter-rouge">start_date</code> will be technically the day they decided to cancel their service.</p>

<div class="responsive-table">

  <table>
    <thead>
      <tr>
        <th>customer_id</th>
        <th>plan_id</th>
        <th>start_date</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>0</td>
        <td>2020-08-01</td>
      </tr>
      <tr>
        <td>1</td>
        <td>1</td>
        <td>2020-08-08</td>
      </tr>
      <tr>
        <td>2</td>
        <td>0</td>
        <td>2020-09-20</td>
      </tr>
      <tr>
        <td>2</td>
        <td>3</td>
        <td>2020-09-27</td>
      </tr>
      <tr>
        <td>11</td>
        <td>0</td>
        <td>2020-11-19</td>
      </tr>
      <tr>
        <td>11</td>
        <td>4</td>
        <td>2020-11-26</td>
      </tr>
      <tr>
        <td>13</td>
        <td>0</td>
        <td>2020-12-15</td>
      </tr>
      <tr>
        <td>13</td>
        <td>1</td>
        <td>2020-12-22</td>
      </tr>
      <tr>
        <td>13</td>
        <td>2</td>
        <td>2021-03-29</td>
      </tr>
      <tr>
        <td>15</td>
        <td>0</td>
        <td>2020-03-17</td>
      </tr>
      <tr>
        <td>15</td>
        <td>2</td>
        <td>2020-03-24</td>
      </tr>
      <tr>
        <td>15</td>
        <td>4</td>
        <td>2020-04-29</td>
      </tr>
      <tr>
        <td>16</td>
        <td>0</td>
        <td>2020-05-31</td>
      </tr>
      <tr>
        <td>16</td>
        <td>1</td>
        <td>2020-06-07</td>
      </tr>
      <tr>
        <td>16</td>
        <td>3</td>
        <td>2020-10-21</td>
      </tr>
      <tr>
        <td>18</td>
        <td>0</td>
        <td>2020-07-06</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
        <td>2020-07-13</td>
      </tr>
      <tr>
        <td>19</td>
        <td>0</td>
        <td>2020-06-22</td>
      </tr>
      <tr>
        <td>19</td>
        <td>2</td>
        <td>2020-06-29</td>
      </tr>
      <tr>
        <td>19</td>
        <td>3</td>
        <td>2020-08-29</td>
      </tr>
    </tbody>
  </table>

</div>

<h2 id="case-study-questions">Case Study Questions</h2>

<p>This case study is split into an initial data understanding question before diving straight into data analysis questions before finishing with 1 single extension challenge.</p>

<h3 id="a-customer-journey">A. Customer Journey</h3>

<p>Based off the 8 sample customers provided in the sample from the <code class="language-plaintext highlighter-rouge">subscriptions</code> table, write a brief description about each customerâ€™s onboarding journey.</p>

<p>Try to keep it as short as possible - you may also want to run some sort of join to make your explanations a bit easier!</p>
<p> customer 1: signed up on 8/1/2020, got the basic monthly plan a week later. customer 2: signed up 9/2/2020, got the pro annual a week later. customer 11: signed up 11/19/2020, did the trial and canceled a week later. customer 13: signed up 12/13/2020, got the basic monthly a week later, 3 months after that switched to pro monthly.customer 15: signed up 3/17/2020, got pro monthly a week later and then canceled within the first month. customer 16: signed up 5/31/2020, switched to basic monthly a week later, almost 4 months after that got pro annual. customer 18: signed up 7/6/2020, got pro monthly a week later. customer 19: signed up 6/22/2020, got pro monthly a week later, then got pro annual within 2 months. </p>

    select orders.customer_id, orders.plan_id,plan_name, price, start_date,
    start_date - lag(start_date,1) over (partition by customer_id order by start_date) as days_between,ranking
    from
    (SELECT customer_id, plan_id, start_date,
    rank() over(partition by customer_id order by start_date) as ranking
    FROM foodie_fi.subscriptions
    where customer_id in(1,2,11,13,15,16,18,19)) orders
    inner join 
    (select * from foodie_fi.plans) plans
    on plans.plan_id = orders.plan_id
    order by customer_id,start_date

<h3 id="b-data-analysis-questions">B. Data Analysis Questions</h3>

1. How many customers has Foodie-Fi ever had?</li>
<p> There have been 1000 customers in the history of Foodie-Fi</p>
---

    select count(*) as tot_custs
    from
    (select customer_id
    from
    (select orders.customer_id, orders.plan_id,plan_name, price, start_date,
    start_date - lag(start_date,1) over (partition by customer_id order by start_date) as days_between,ranking
    from
    (SELECT customer_id, plan_id, start_date,
    rank() over(partition by customer_id order by start_date) as ranking
    FROM foodie_fi.subscriptions) orders
    inner join 
    (select * from foodie_fi.plans) plans
    on plans.plan_id = orders.plan_id
    order by customer_id,start_date) base1
    group by customer_id) custs

| tot_custs |
| --------- |
| 1000      |

2. What is the monthly distribution of trial plan start_date values for our dataset - use the start of the month as the group by value?
<p> This looks fairly uniform through the year. </p>

---

	select cast(concat(extract(month from start_date),'/01/',extract(year from start_date)) as date) as month_beg,
    count(*) as trials_in_month
    from
    (select orders.customer_id, orders.plan_id,plan_name, price, start_date,
    start_date - lag(start_date,1) over (partition by customer_id order by start_date) as days_between,ranking
    from
    (SELECT customer_id, plan_id, start_date,
    rank() over(partition by customer_id order by start_date) as ranking
    FROM foodie_fi.subscriptions) orders
    inner join 
    (select * from foodie_fi.plans) plans
    on plans.plan_id = orders.plan_id
    order by customer_id,start_date) base1
    where plan_name= 'trial'
    group by 1
    order by 1    
    
| month_beg                | trials_in_month |
| ------------------------ | --------------- |
| 2020-01-01T00:00:00.000Z | 88              |
| 2020-02-01T00:00:00.000Z | 68              |
| 2020-03-01T00:00:00.000Z | 94              |
| 2020-04-01T00:00:00.000Z | 81              |
| 2020-05-01T00:00:00.000Z | 88              |
| 2020-06-01T00:00:00.000Z | 79              |
| 2020-07-01T00:00:00.000Z | 89              |
| 2020-08-01T00:00:00.000Z | 88              |
| 2020-09-01T00:00:00.000Z | 87              |
| 2020-10-01T00:00:00.000Z | 79              |
| 2020-11-01T00:00:00.000Z | 75              |
| 2020-12-01T00:00:00.000Z | 84              |

3. What plan start_date values occur after the year 2020 for our dataset? Show the breakdown by count of events for each plan_name?
<p> This shows the month begin date, and each plans count, including churn, gor each month in 2021.</p>
---

	select cast(concat(extract(month from start_date),'/01/',extract(year from start_date)) as date) as month_beg,plan_name,
    count(*) as started_month
    from
    (select orders.customer_id, orders.plan_id,plan_name, price, start_date,
    start_date - lag(start_date,1) over (partition by customer_id order by start_date) as days_between,ranking
    from
    (SELECT customer_id, plan_id, start_date,
    rank() over(partition by customer_id order by start_date) as ranking
    FROM foodie_fi.subscriptions) orders
    inner join 
    (select * from foodie_fi.plans) plans
    on plans.plan_id = orders.plan_id
    order by customer_id,start_date) base1
    where cast(concat(extract(month from start_date),'/01/',extract(year from start_date)) as date)> '12/01/2020'
    group by 1,2,plan_id
    order by 1,plan_id
    
| month_beg                | plan_name     | started_month |
| ------------------------ | ------------- | ------------- |
| 2021-01-01T00:00:00.000Z | basic monthly | 8             |
| 2021-01-01T00:00:00.000Z | pro monthly   | 26            |
| 2021-01-01T00:00:00.000Z | pro annual    | 24            |
| 2021-01-01T00:00:00.000Z | churn         | 19            |
| 2021-02-01T00:00:00.000Z | pro monthly   | 12            |
| 2021-02-01T00:00:00.000Z | pro annual    | 17            |
| 2021-02-01T00:00:00.000Z | churn         | 18            |
| 2021-03-01T00:00:00.000Z | pro monthly   | 15            |
| 2021-03-01T00:00:00.000Z | pro annual    | 9             |
| 2021-03-01T00:00:00.000Z | churn         | 21            |
| 2021-04-01T00:00:00.000Z | pro monthly   | 7             |
| 2021-04-01T00:00:00.000Z | pro annual    | 13            |
| 2021-04-01T00:00:00.000Z | churn         | 13            |

4. What is the customer count and percentage of customers who have churned rounded to 1 decimal place?
<p> 307, or 30.7% of customers have churned in total </p>
---

	select sum(churned) as churned_cust, count(*) count_cust, round(((sum(churned)/count(*))*100),1) as per_churned
    from
    (select customer_id,sum(case when plan_name in('churn') then 1 else 0 end) as churned
    from
    (select orders.customer_id, orders.plan_id,plan_name, price, start_date,
    start_date - lag(start_date,1) over (partition by customer_id order by start_date) as days_between,ranking
    from
    (SELECT customer_id, plan_id, start_date,
    rank() over(partition by customer_id order by start_date) as ranking
    FROM foodie_fi.subscriptions) orders
    inner join 
    (select * from foodie_fi.plans) plans
    on plans.plan_id = orders.plan_id
    order by customer_id,start_date) base1
    group by customer_id) tots
    
| churned_cust | count_cust | per_churned |
| ------------ | ---------- | ----------- |
| 307          | 1000       | 30.7        |

5. How many customers have churned straight after their initial free trial - what percentage is this rounded to the nearest whole number?
<p> 92 customers in total churned ater the free trial. This is found out as they have a plan_name of churn as ranking number 2 in my query. </p>
---
	select sum(churned) as churned_cust, count(*) count_cust, round(((sum(churned)/count(*))*100),1) as per_churned
    from
    (select customer_id,sum(case when ranking = 2 and plan_name ='churn' then 1 else 0 end) as churned
    from
    (select orders.customer_id, orders.plan_id,plan_name, price, start_date,
    start_date - lag(start_date,1) over (partition by customer_id order by start_date) as days_between,ranking
    from
    (SELECT customer_id, plan_id, start_date,
    rank() over(partition by customer_id order by start_date) as ranking
    FROM foodie_fi.subscriptions) orders
    inner join 
    (select * from foodie_fi.plans) plans
    on plans.plan_id = orders.plan_id
    order by customer_id,start_date) base1
    group by customer_id) tots
    
| churned_cust | count_cust | per_churned |
| ------------ | ---------- | ----------- |
| 92           | 1000       | 9.2         |

  <li>What is the number and percentage of customer plans after their initial free trial?</li>
  <li>What is the customer count and percentage breakdown of all 5 <code class="language-plaintext highlighter-rouge">plan_name</code> values at <code class="language-plaintext highlighter-rouge">2020-12-31</code>?</li>
  <li>How many customers have upgraded to an annual plan in 2020?</li>
  <li>How many days on average does it take for a customer to an annual plan from the day they join Foodie-Fi?</li>
  <li>Can you further breakdown this average value into 30 day periods (i.e. 0-30 days, 31-60 days etc)</li>
  <li>How many customers downgraded from a pro monthly to a basic monthly plan in 2020?</li>
</ol>

<h3 id="c-challenge-payment-question">C. Challenge Payment Question</h3>

<p>The Foodie-Fi team wants you to create a new <code class="language-plaintext highlighter-rouge">payments</code> table for the year 2020 that includes amounts paid by each customer in the <code class="language-plaintext highlighter-rouge">subscriptions</code> table with the following requirements:</p>

<ul>
  <li>monthly payments always occur on the same day of month as the original <code class="language-plaintext highlighter-rouge">start_date</code> of any monthly paid plan</li>
  <li>upgrades from basic to monthly or pro plans are reduced by the current paid amount in that month and start immediately</li>
  <li>upgrades from pro monthly to pro annual are paid at the end of the current billing period and also starts at the end of the month period</li>
  <li>once a customer churns they will no longer make payments</li>
</ul>

<p>Example outputs for this table might look like the following:</p>

<div class="responsive-table">

  <table>
    <thead>
      <tr>
        <th>customer_id</th>
        <th>plan_id</th>
        <th>plan_name</th>
        <th>payment_date</th>
        <th>amount</th>
        <th>payment_order</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-08-08</td>
        <td>9.90</td>
        <td>1</td>
      </tr>
      <tr>
        <td>1</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-09-08</td>
        <td>9.90</td>
        <td>2</td>
      </tr>
      <tr>
        <td>1</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-10-08</td>
        <td>9.90</td>
        <td>3</td>
      </tr>
      <tr>
        <td>1</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-11-08</td>
        <td>9.90</td>
        <td>4</td>
      </tr>
      <tr>
        <td>1</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-12-08</td>
        <td>9.90</td>
        <td>5</td>
      </tr>
      <tr>
        <td>2</td>
        <td>3</td>
        <td>pro annual</td>
        <td>2020-09-27</td>
        <td>199.00</td>
        <td>1</td>
      </tr>
      <tr>
        <td>13</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-12-22</td>
        <td>9.90</td>
        <td>1</td>
      </tr>
      <tr>
        <td>15</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-03-24</td>
        <td>19.90</td>
        <td>1</td>
      </tr>
      <tr>
        <td>15</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-04-24</td>
        <td>19.90</td>
        <td>2</td>
      </tr>
      <tr>
        <td>16</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-06-07</td>
        <td>9.90</td>
        <td>1</td>
      </tr>
      <tr>
        <td>16</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-07-07</td>
        <td>9.90</td>
        <td>2</td>
      </tr>
      <tr>
        <td>16</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-08-07</td>
        <td>9.90</td>
        <td>3</td>
      </tr>
      <tr>
        <td>16</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-09-07</td>
        <td>9.90</td>
        <td>4</td>
      </tr>
      <tr>
        <td>16</td>
        <td>1</td>
        <td>basic monthly</td>
        <td>2020-10-07</td>
        <td>9.90</td>
        <td>5</td>
      </tr>
      <tr>
        <td>16</td>
        <td>3</td>
        <td>pro annual</td>
        <td>2020-10-21</td>
        <td>189.10</td>
        <td>6</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-07-13</td>
        <td>19.90</td>
        <td>1</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-08-13</td>
        <td>19.90</td>
        <td>2</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-09-13</td>
        <td>19.90</td>
        <td>3</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-10-13</td>
        <td>19.90</td>
        <td>4</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-11-13</td>
        <td>19.90</td>
        <td>5</td>
      </tr>
      <tr>
        <td>18</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-12-13</td>
        <td>19.90</td>
        <td>6</td>
      </tr>
      <tr>
        <td>19</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-06-29</td>
        <td>19.90</td>
        <td>1</td>
      </tr>
      <tr>
        <td>19</td>
        <td>2</td>
        <td>pro monthly</td>
        <td>2020-07-29</td>
        <td>19.90</td>
        <td>2</td>
      </tr>
      <tr>
        <td>19</td>
        <td>3</td>
        <td>pro annual</td>
        <td>2020-08-29</td>
        <td>199.00</td>
        <td>3</td>
      </tr>
    </tbody>
  </table>

</div>

<h3 id="d-outside-the-box-questions">D. Outside The Box Questions</h3>

<p>The following are open ended questions which might be asked during a technical interview for this case study - there are no right or wrong answers, but answers that make sense from both a technical and a business perspective make an amazing impression!</p>

<ol>
  <li>How would you calculate the rate of growth for Foodie-Fi?</li>
  <li>What key metrics would you recommend Foodie-Fi management to track over time to assess performance of their overall business?</li>
  <li>What are some key customer journeys or experiences that you would analyse further to improve customer retention?</li>
  <li>If the Foodie-Fi team were to create an exit survey shown to customers who wish to cancel their subscription, what questions would you include in the survey?</li>
  <li>What business levers could the Foodie-Fi team use to reduce the customer churn rate? How would you validate the effectiveness of your ideas?</li>
</ol>